# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  precision: 16-mixed
  devices: [0,]
  num_nodes: 1
  # max_epochs: 10
  check_val_every_n_epoch: 1
  val_check_interval: 0.25
  log_every_n_steps: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: eurosat-sara
model:
  model_name: vit-b16-224-in21k
  training_mode: sara
  optimizer: adamw
  lr: 3e-1
  weight_decay: 1e-5
  scheduler: cosine
  warmup_steps: 100

data:
  dataset: eurosat
  root: data/
  size: 224
  batch_size: 128
  workers: 8
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true